/**
 * Inline Expo config plugin — pin the iOS code-signing team.
 *
 * The Apple ID signed into Xcode belongs to two teams: a free "Personal Team"
 * (D74ULG6962) and the paid org "RHK Properties LLC" (UFYQ4RL447). `expo
 * run:ios` / Xcode automatic signing auto-pick the personal team, which CANNOT
 * use the Push Notifications capability — the build then fails with:
 *
 *   Personal development teams ... do not support the Push Notifications capability.
 *
 * `ios/` is regenerated by `expo prebuild`, so we stamp DEVELOPMENT_TEAM onto
 * every build config on each prebuild to force the paid team. iOS-only; on
 * Android `withXcodeProject` is a no-op (there is no Xcode project).
 */
const { withXcodeProject } = require('expo/config-plugins');

const APPLE_TEAM_ID = 'UFYQ4RL447'; // RHK Properties LLC (paid) — supports push

module.exports = function withIosSigningTeam(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const buildConfigs = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(buildConfigs)) {
      const settings = buildConfigs[key].buildSettings;
      // Only real targets carry a bundle id; skip the project-level configs.
      if (settings && settings.PRODUCT_BUNDLE_IDENTIFIER) {
        settings.DEVELOPMENT_TEAM = APPLE_TEAM_ID;
      }
    }
    return cfg;
  });
};
