/**
 * Inline Expo config plugin — Chucker (native Android HTTP inspector).
 *
 * Why this exists: react-native-network-logger gives an in-app log SCREEN but
 * cannot show a status-bar notification. Chucker (native, Android-only) hooks
 * React Native's underlying OkHttp client and shows a persistent notification
 * that opens a full request inspector — the Chucker experience testers expect.
 *
 * `android/` is generated by `expo prebuild` and gitignored, so the Gradle dep
 * and the MainApplication wiring must be (re)injected on every prebuild. This
 * plugin does that.
 *
 * Gating: native capture is compiled behind `BuildConfig.ENABLE_NETWORK_LOGGER`,
 * whose value mirrors the JS-side `.env` flag EXPO_PUBLIC_ENABLE_NETWORK_LOGGER
 * read at prebuild time. Tester APK (flag=true) → Chucker on; prod build
 * (flag unset) → the interceptor is never attached. Re-run prebuild after
 * changing the flag, since the value is baked into BuildConfig at compile time.
 *
 * POST_NOTIFICATIONS is already declared in app.json android.permissions.
 */

const { withAppBuildGradle, withMainApplication } = require('@expo/config-plugins');

const CHUCKER_VERSION = '4.0.0';
const CHUCKER_DEP = `com.github.chuckerteam.chucker:library:${CHUCKER_VERSION}`;

function isEnabled() {
  return process.env.EXPO_PUBLIC_ENABLE_NETWORK_LOGGER === 'true';
}

/** Add the Chucker Gradle dependency + the BuildConfig gate flag. */
const withChuckerGradle = (config) =>
  withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // 1. Dependency — insert once into the dependencies { } block.
    if (!contents.includes(CHUCKER_DEP)) {
      contents = contents.replace(
        /dependencies\s*{/,
        `dependencies {\n    implementation("${CHUCKER_DEP}")`,
      );
    }

    // 2. BuildConfig flag — insert once into defaultConfig { }.
    if (!contents.includes('ENABLE_NETWORK_LOGGER')) {
      contents = contents.replace(
        /defaultConfig\s*{/,
        `defaultConfig {\n        buildConfigField "boolean", "ENABLE_NETWORK_LOGGER", "${isEnabled()}"`,
      );
    } else {
      // Keep the flag in sync with the current env on re-prebuild.
      contents = contents.replace(
        /buildConfigField "boolean", "ENABLE_NETWORK_LOGGER", "(true|false)"/,
        `buildConfigField "boolean", "ENABLE_NETWORK_LOGGER", "${isEnabled()}"`,
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

const CHUCKER_SNIPPET = `    // Chucker — attach to RN's OkHttp client so HTTP traffic surfaces in the
    // status-bar notification. Must run before RN networking initialises.
    if (BuildConfig.ENABLE_NETWORK_LOGGER) {
      com.facebook.react.modules.network.OkHttpClientProvider.setOkHttpClientFactory(
        object : com.facebook.react.modules.network.OkHttpClientFactory {
          override fun createNewNetworkModuleClient(): okhttp3.OkHttpClient =
            com.facebook.react.modules.network.OkHttpClientProvider
              .createClientBuilder(applicationContext)
              .addInterceptor(
                com.chuckerteam.chucker.api.ChuckerInterceptor.Builder(applicationContext).build()
              )
              .build()
        }
      )
    }
`;

/** Inject the OkHttp factory override into MainApplication.onCreate. */
const withChuckerMainApplication = (config) =>
  withMainApplication(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error('[withChucker] expected Kotlin MainApplication.');
    }
    let contents = cfg.modResults.contents;
    if (contents.includes('ChuckerInterceptor')) return cfg; // idempotent

    // Insert before loadReactNative(this) so the factory is set first.
    const anchor = 'loadReactNative(this)';
    if (!contents.includes(anchor)) {
      throw new Error('[withChucker] could not find loadReactNative(this) anchor.');
    }
    contents = contents.replace(anchor, `${CHUCKER_SNIPPET}\n    ${anchor}`);
    cfg.modResults.contents = contents;
    return cfg;
  });

/** @type {import('@expo/config-plugins').ConfigPlugin} */
const withChucker = (config) => withChuckerMainApplication(withChuckerGradle(config));

module.exports = withChucker;
