/**
 * Inline Expo config plugin — Android release signing (EAS upload keystore).
 *
 * Why this exists: the Play upload key is the EAS-managed keystore. A local
 * Gradle release build MUST sign with that exact key or Play rejects the upload
 * ("signed with the wrong key"). But `android/` is generated by `expo prebuild`
 * and gitignored, so the keystore file, the `gradle.properties` secrets, and the
 * `release` signingConfig are ALL wiped on every `prebuild --clean`. Before this
 * plugin, every prebuild meant re-downloading the keystore via `eas credentials`
 * and hand-editing three files. This plugin re-applies all of it automatically.
 *
 * Secrets live in the gitignored `.secrets/` folder (NOT committed). Signing is
 * PER-ENVIRONMENT because QA and PROD are different Play apps with different
 * upload keys (`com.rhkproperties.mobile.qa` vs `com.rhkproperties.mobile`).
 * Selected by APP_ENV, mirroring app.config.js:
 *   .secrets/qa/release.keystore + .secrets/qa/keystore.json      → APP_ENV=qa
 *   .secrets/prod/release.keystore + .secrets/prod/keystore.json  → APP_ENV=production
 * Legacy fallback (production only): a keystore.json at the `.secrets/` root is
 * still honored so existing prod builds keep working without moving files.
 *
 * keystore.json shape: { storeFile, keyAlias, storePassword, keyPassword }.
 *
 * If no keystore.json is found for the active env the plugin is a no-op (e.g.
 * CI / EAS cloud builds that manage their own credentials), so it never breaks
 * those, and a QA build with no QA keystore falls back to debug signing.
 *
 * versionCode: set `expo.android.versionCode` in app.json — prebuild writes it
 * into build.gradle. Bump it there before each Play upload (Play requires a
 * strictly higher code every time).
 */

const fs = require('node:fs');
const path = require('node:path');
const {
  withAppBuildGradle,
  withGradleProperties,
  withDangerousMod,
} = require('@expo/config-plugins');

/** Map APP_ENV to its .secrets subfolder. Mirrors app.config.js resolveAppEnv. */
function envDirName() {
  return process.env.APP_ENV === 'production' ? 'prod' : 'qa';
}

/**
 * Resolve the active env's signing secrets. Returns `{ secrets, baseDir }` where
 * baseDir is the folder holding the keystore file, or null if none configured.
 * Order: `.secrets/<env>/keystore.json`, then (production only) the legacy
 * `.secrets/keystore.json` at the root.
 */
function readSecrets(projectRoot) {
  const env = envDirName();
  const candidates = [path.join(projectRoot, '.secrets', env)];
  if (env === 'prod') candidates.push(path.join(projectRoot, '.secrets'));
  for (const baseDir of candidates) {
    const file = path.join(baseDir, 'keystore.json');
    if (fs.existsSync(file)) {
      return { secrets: JSON.parse(fs.readFileSync(file, 'utf8')), baseDir };
    }
  }
  return null;
}

const SIGNING_CONFIG = `        release {
            if (project.hasProperty('RELEASE_STORE_FILE')) {
                storeFile file(RELEASE_STORE_FILE)
                storePassword RELEASE_STORE_PASSWORD
                keyAlias RELEASE_KEY_ALIAS
                keyPassword RELEASE_KEY_PASSWORD
            }
        }
`;

/** Add the `release` signingConfig + point the release buildType at it. */
const withSigningGradle = (config, secrets) =>
  withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // 1. Add a `release` block into signingConfigs { } (idempotent). Guard on a
    //    string unique to our block — a generic `release {` check would falsely
    //    match the release buildType further down and skip the insertion.
    if (!contents.includes('storeFile file(RELEASE_STORE_FILE)')) {
      contents = contents.replace(/signingConfigs\s*{\n/, `signingConfigs {\n${SIGNING_CONFIG}`);
    }

    // 2. Point the release buildType at it, falling back to debug if the
    //    RELEASE_* props are absent. Target the release buildType's
    //    `signingConfig signingConfigs.debug` (the debug buildType also has one,
    //    so match the one that follows `release {`).
    if (!contents.includes('? signingConfigs.release :')) {
      contents = contents.replace(
        /(buildTypes\s*{[\s\S]*?release\s*{[\s\S]*?)signingConfig signingConfigs\.debug/,
        `$1signingConfig project.hasProperty('RELEASE_STORE_FILE') ? signingConfigs.release : signingConfigs.debug`,
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

/** Write RELEASE_* secrets into android/gradle.properties. */
const withSigningGradleProperties = (config, secrets) =>
  withGradleProperties(config, (cfg) => {
    const props = {
      RELEASE_STORE_FILE: secrets.storeFile,
      RELEASE_KEY_ALIAS: secrets.keyAlias,
      RELEASE_STORE_PASSWORD: secrets.storePassword,
      RELEASE_KEY_PASSWORD: secrets.keyPassword,
    };
    for (const [key, value] of Object.entries(props)) {
      const existing = cfg.modResults.find((item) => item.type === 'property' && item.key === key);
      if (existing) {
        existing.value = value;
      } else {
        cfg.modResults.push({ type: 'property', key, value });
      }
    }
    return cfg;
  });

/** Copy the active env's keystore into android/app/ on every prebuild. */
const withKeystoreFile = (config, secrets, baseDir) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const src = path.join(baseDir, secrets.storeFile);
      const dest = path.join(cfg.modRequest.platformProjectRoot, 'app', secrets.storeFile);
      if (!fs.existsSync(src)) {
        throw new Error(`[withAndroidSigning] keystore missing at ${src}`);
      }
      fs.copyFileSync(src, dest);
      return cfg;
    },
  ]);

/** @type {import('@expo/config-plugins').ConfigPlugin} */
const withAndroidSigning = (config) => {
  const resolved = readSecrets(config._internal?.projectRoot ?? process.cwd());
  if (!resolved) {
    // No local signing configured for this env — leave default debug signing.
    return config;
  }
  const { secrets, baseDir } = resolved;
  config = withSigningGradle(config, secrets);
  config = withSigningGradleProperties(config, secrets);
  config = withKeystoreFile(config, secrets, baseDir);
  return config;
};

module.exports = withAndroidSigning;
