/**
 * Inline Expo config plugin — fix `@react-native-firebase` + `useFrameworks: static`.
 *
 * With static frameworks (required by Firebase's Swift pods), the RNFB Obj-C
 * headers `#import <React/RCTConvert.h>` etc. trip
 * `-Wnon-modular-include-in-framework-module`, which RN promotes to an error
 * (`-Werror`), failing the iOS build:
 *
 *   include of non-modular header inside framework module
 *   'RNFBApp.RCTConvert_FIRApp': '.../React-Core/React/RCTConvert.h'
 *
 * Two pieces, both required:
 *  1. `$RNFirebaseAsStaticFramework = true` at the top of the Podfile — required
 *     for RNFirebase v9+ under `use_frameworks!`. Without it the RNFB modules
 *     can't resolve React types (`RCT_EXPORT_METHOD` macro fails to expand,
 *     "RCTPromiseRejectBlock must be imported from module … before required").
 *  2. `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES` on the Pods
 *     targets — silences the `-Wnon-modular-include` error on `<React/…>` headers.
 *
 * `ios/` is regenerated by `expo prebuild`, so we patch the Podfile on every
 * prebuild rather than by hand.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

const STATIC_FRAMEWORK_GLOBAL = '$RNFirebaseAsStaticFramework = true';
const FLAG = 'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES';

const INJECT = `    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['${FLAG}'] = 'YES'
      end
    end
`;

/** @type {import('@expo/config-plugins').ConfigPlugin} */
const withFirebaseStaticFix = (config) =>
  withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfilePath, 'utf8');

      // 1. Global, read by the RNFB podspec during pod install — set at top.
      if (!contents.includes(STATIC_FRAMEWORK_GLOBAL)) {
        contents = `${STATIC_FRAMEWORK_GLOBAL}\n${contents}`;
      }

      // 2. Allow non-modular includes on the Pods targets (post_install).
      if (!contents.includes(FLAG)) {
        const anchor = 'post_install do |installer|\n';
        const idx = contents.indexOf(anchor);
        if (idx === -1) {
          throw new Error('[withFirebaseStaticFix] could not find post_install block in Podfile.');
        }
        const insertAt = idx + anchor.length;
        contents = contents.slice(0, insertAt) + INJECT + contents.slice(insertAt);
      }

      fs.writeFileSync(podfilePath, contents);
      return cfg;
    },
  ]);

module.exports = withFirebaseStaticFix;
