/**
 * Inline Expo config plugin — react-native-callkeep (Android ConnectionService).
 *
 * Why this exists: `android/` is generated by `expo prebuild` and is gitignored,
 * so any hand-edit to AndroidManifest.xml is wiped on the next `prebuild --clean`.
 * react-native-callkeep does NOT declare its own `VoiceConnectionService` in its
 * bundled manifest (it only ships permissions) — the host app must register it.
 * This plugin injects that <service> on every prebuild so it always survives.
 *
 * It deliberately does NOT register any FirebaseMessagingService: cold-killed
 * incoming-call wake is handled in JS via @react-native-firebase/messaging's
 * `setBackgroundMessageHandler` (see src/features/callService/services/
 * fcm-call-messaging.ts), which boots a headless JS task and can then call
 * `RNCallKeep.displayIncomingCall(...)`. A native Kotlin service cannot show the
 * UI from a cold start because callkeep's module `instance` is null until JS
 * runs `RNCallKeep.setup()`.
 *
 * Required permissions (MANAGE_OWN_CALLS, FOREGROUND_SERVICE*, USE_FULL_SCREEN_INTENT,
 * etc.) are declared in app.json `android.permissions` — not duplicated here.
 */

const { withAndroidManifest } = require('@expo/config-plugins');

const CONNECTION_SERVICE_NAME = 'io.wazo.callkeep.VoiceConnectionService';

/** @param {import('@expo/config-plugins').AndroidConfig.Manifest.ManifestApplication} application */
function addVoiceConnectionService(application, appLabel) {
  application.service = application.service ?? [];

  const exists = application.service.some(
    (service) => service?.$?.['android:name'] === CONNECTION_SERVICE_NAME,
  );
  if (exists) return;

  application.service.push({
    $: {
      'android:name': CONNECTION_SERVICE_NAME,
      'android:label': appLabel,
      'android:permission': 'android.permission.BIND_TELECOM_CONNECTION_SERVICE',
      // Android 14+ requires the FGS type; the mid-call mic service is microphone-only.
      'android:foregroundServiceType': 'microphone',
      'android:exported': 'true',
    },
    'intent-filter': [
      {
        action: [{ $: { 'android:name': 'android.telecom.ConnectionService' } }],
      },
    ],
  });
}

/**
 * Allow MainActivity to be launched over the lock screen with the screen off —
 * required for the notifee `fullScreenAction` incoming-call wake. Without these
 * the OS downgrades the full-screen intent to a heads-up banner even when the
 * device is locked.
 *
 * @param {import('@expo/config-plugins').AndroidConfig.Manifest.ManifestApplication} application
 */
function addLockScreenActivityAttrs(application) {
  const mainActivity = (application.activity ?? []).find(
    (activity) => activity?.$?.['android:name'] === '.MainActivity',
  );
  if (!mainActivity) {
    throw new Error('[withCallKeep] AndroidManifest is missing .MainActivity.');
  }
  mainActivity.$['android:showWhenLocked'] = 'true';
  mainActivity.$['android:turnScreenOn'] = 'true';
}

/** @type {import('@expo/config-plugins').ConfigPlugin} */
const withCallKeep = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (!application) {
      throw new Error('[withCallKeep] AndroidManifest is missing <application>.');
    }
    const appLabel = config.name ?? 'RHK Properties';
    addVoiceConnectionService(application, appLabel);
    addLockScreenActivityAttrs(application);
    return cfg;
  });

module.exports = withCallKeep;
